### ISSUE TITLE
'pip install' fails with "No matching distribution found for czds"

### ISSUE THREAD

**Issue by bill-e-ghote** [MSAdministrator/czds#16]
I'm trying to install on Miniconda (Python 3.9.12) on Windows 10 enterprise system where I don't have local admin (I don't think that's relevant, but who knows). It's failing (see screenshot). In my local proxy logs (I'm using Burpsuite Community to debug and bypass Zscaler), I see requests to https://pypi.org/simple/czds/ are returning 404 errors, so I guess it's not there?

Please advise. 
![image](https://user-images.githubusercontent.com/2491041/217384215-e3cab296-0480-4998-83ed-d21bef78778b.png)

**Comment by MSAdministrator** [comment]
@bill-e-ghote FYI, the first published version is now on pypi - you can install it using ```pip install czds```
